/**
 * D1 table: `profile` (always one row, id = 1).
 *
 * Holds the user's long-lived taste model. The Reflector agent proposes
 * mutations to this row after every inbound feedback message; the Curator
 * reads it each morning when picking the day's phrases.
 *
 * `themes` and `no_list` are stored as JSON-serialised strings because D1
 * does not have a native array type.
 */
export interface Profile {
  id: number;                  // always 1
  regional_preference: string; // e.g. "general", "Mexico", "Spain", "Caribbean"
  vulgarity_tolerance: number; // 0 = none, 1 = mild, 2 = moderate, 3 = high
  themes: string;              // JSON-serialised string[]: ["love","work","animals","food"]
  common_vs_obscure: number;   // 0 = very common, 10 = very obscure
  no_list: string;             // JSON-serialised string[] of phrase IDs that bombed
  updated_at: string;          // ISO-8601
}

/**
 * D1 table: `idiom_history` (one row per daily send).
 *
 * Written by the Orchestrator immediately after composing each day's message.
 * Scout reads this table to deduplicate — it never suggests a phrase whose id
 * already appears in history. The Curator also reads recent rows to understand
 * what the user has already seen and how they rated it.
 *
 * `user_rating` and `user_feedback` start null; they are available for a
 * future inbound feedback channel to populate.
 */
export interface IdiomHistory {
  id: number;
  sent_at: string;
  idiom_id: string;
  idiom_text: string;
  colloquialism_id: string;
  colloquialism_text: string;
  curator_justification: string;
  user_rating: number | null;  // 1–5 or null
  user_feedback: string | null;
}

/**
 * One phrase candidate generated by the Scout AI agent.
 *
 * This is NOT a D1 table. Scout calls an LLM — guided by the user's current
 * Profile (region, theme, vulgarity_tolerance, common_vs_obscure) — to produce
 * a pool of fresh candidate phrases each morning. Scout also instructs the LLM
 * to avoid any `id` already present in `idiom_history`, ensuring no phrase is
 * sent twice over the lifetime of the app.
 *
 * The filtered candidate list is then forwarded to the Curator (a second LLM
 * call with forced tool use), which picks exactly one idiom and one
 * colloquialism, returning a `CuratorVerdict`.
 *
 * `id` is a stable kebab-case identifier assigned by Scout (e.g.
 * `"el-que-no-llora-no-mama"`). It is stored in `idiom_history.idiom_id` and
 * `idiom_history.colloquialism_id` to enable lifetime deduplication.
 */
export interface SeedPhrase {
  id: string;                              // kebab-case, stable across generations
  text: string;                            // the phrase in Spanish
  type: "idiom" | "colloquialism";
  region: string;                          // "general", "Mexico", "Spain", etc.
  theme: string;                           // "love", "work", "animals", "food", "misc"
  vulgarity_level: number;                 // 0–3
}

/**
 * Structured output returned by the Curator AI agent (forced tool use).
 *
 * The Curator receives a filtered candidate list from Scout and the user's
 * current Profile, then picks exactly one idiom and one colloquialism.
 * Each pick includes the phrase's seed-list id and text so the Orchestrator
 * can write them straight into `idiom_history` without a second lookup.
 *
 * The Anthropic SDK enforces this shape at the call boundary via
 * `tool_choice: { type: "tool", name: "..." }` — a malformed response throws
 * rather than being silently swallowed.
 */
export interface CuratorVerdict {
  idiom: { id: string; text: string; justification: string };
  colloquialism: { id: string; text: string; justification: string };
}

/**
 * Structured output returned by the Feedback AI agent.
 *
 * Parses freeform reply text into structured feedback signals (sentiment,
 * style preferences, theme mentions). This is a transient analysis value —
 * never stored in D1 directly. Callers hold the relevant `IdiomHistory` row
 * id in scope and write `user_rating` / `user_feedback` to D1 themselves;
 * carrying the id here too would be redundant coupling.
 */
export interface FeedbackResult {
  sentiment: "positive" | "negative" | "neutral" | "mixed";
  wants_more_colloquial: boolean | null;
  wants_more_formal: boolean | null;
  wants_more_vulgar: boolean | null;
  wants_less_vulgar: boolean | null;
  theme_mentions: string[];
  raw: string;
}

/**
 * Structured output returned by the Reflector AI agent.
 *
 * After the Feedback agent parses a user reply, the Reflector decides which
 * `Profile` fields to mutate and by how much. All fields are optional — the
 * Reflector only proposes changes it has evidence for; unset fields are left
 * untouched in D1.
 */
export interface ReflectorProposal {
  regional_preference?: string;
  vulgarity_tolerance?: number;
  themes?: string[];
  common_vs_obscure?: number;
  no_list_additions?: string[];
}

/**
 * The data required to INSERT one row into `idiom_history`.
 *
 * Omits `id` (autoincrement), `sent_at` (defaulted by the DB to `datetime('now')`),
 * and the feedback columns (`user_rating`, `user_feedback`) which start null and
 * are written later via the webhook flow.
 */
export interface IdiomHistoryInsert {
  idiom_id: string;
  idiom_text: string;
  colloquialism_id: string;
  colloquialism_text: string;
  curator_justification: string;
}

/**
 * Cloudflare Worker bindings injected at runtime.
 *
 * `DB` is the D1 database bound via `[[d1_databases]]` in `wrangler.toml`.
 * All string fields are stored as Wrangler secrets (`wrangler secret put`)
 * and are never read from `process.env`.
 *
 * NTFY_TOPIC is the ntfy.sh topic name used as the delivery channel. The
 * worker POSTs to https://ntfy.sh/<NTFY_TOPIC> to send push notifications.
 * On the free tier the URL is the shared secret — choose a long random name.
 */
export interface Env {
  DB: D1Database;
  ANTHROPIC_API_KEY: string;
  // ntfy.sh topic for push delivery. Set with `wrangler secret put NTFY_TOPIC`.
  NTFY_TOPIC: string;
  // Shared secret for POST /trigger. The caller must send
  //   Authorization: Bearer <TRIGGER_SECRET>
  // Set with `wrangler secret put TRIGGER_SECRET`.
  TRIGGER_SECRET: string;
}
